<?php

/**
 * This file was generated by DAMB
 *
 * @copyright   Copyright (c) 2019 - 2020, AXeL-dev
 * @license     GPL
 * @link        https://github.com/AXeL-dev/damb
 */

// Load Dolibarr environment (mandatory)
if (false === (@include_once '../../main.inc.php')) { // From htdocs directory
    require_once '../../../main.inc.php'; // From "custom" directory
}

// Load page & musac lib
dol_include_once('musac/lib/page.lib.php');
dol_include_once('musac/lib/musac.lib.php');
dol_include_once('musac/lib/dolistore.lib.php');

// Load module class
dol_include_once('musac/core/modules/modMuSac.class.php');

// Control access to page
control_access('$user->admin');

/**
 * View
 */

print_header('About', array('admin', 'musac@musac'));

print_subtitle('About', 'title_generic.png', 'link:modules_list');

print_admin_tabs('About');

$module = new modMuSac(null);

load_template('musac/tpl/about.tpl.php', array(
    'module_name' => $module->name,
    'module_desc' => $module->description,
    'module_picture' => 'musac.jpg@musac',
    'module_version' => $module->version,
    'module_url' => 'https://github.com/omegjunior/MuSac',
    'author_name' => $module->editor_name,
    'author_url' => $module->editor_url,
    'author_email' => 'omegajunior.apps@gmail.com',
    'author_dolistore_url' => '#'
));

print_footer(true);
