<?php

/**
 * This file was generated by DAMB
 *
 * @copyright   Copyright (c) 2019 - 2020, AXeL-dev
 * @license     GPL
 * @link        https://github.com/AXeL-dev/damb
 */

require_once DOL_DOCUMENT_ROOT . '/core/class/commondocgenerator.class.php';
require_once DOL_DOCUMENT_ROOT . '/core/lib/functions2.lib.php';

/**
 * ModeleMuSac class
 */
abstract class ModeleMuSac extends CommonDocGenerator
{
    /**
     * Return list of active generation models
     *
     * @param   DoliDB      $db                     Database handler
     * @param   integer     $maxfilenamelength      Max length of value to show
     * @return  array                               List of templates
     */
    public static function liste_modeles($db, $maxfilenamelength=0)
    {
        $list = getListOfModels($db, 'musac', $maxfilenamelength);

        return $list;
    }
}

// FIX for Dolibarr >= 8
abstract class ModelePDFMuSac extends ModeleMuSac {}
